### ISSUE TITLE
ZF Model

### ISSUE THREAD

**Issue by bkj** [imatge-upc/retrieval-2016-deepvision#4]
Hi

Do you have examples of what the `params.py` file should look like for the `ZF` model, rather than the `VGG` model.  I could probably track down the appropriate `prototxt` file myself, but I want to make sure I'm not making some mistake.

Thanks!
Ben

**Comment by amaiasalvador** [comment]
Hi,

[Here](https://github.com/rbgirshick/py-faster-rcnn/blob/master/models/pascal_voc/ZF/faster_rcnn_end2end/test.prototxt)'s the prototxt file for the ZF model. As for the model weights, I believe that they are downloaded together with the VGG ones when you run `data/models/fetch_models.sh`. 

For the parameters, you just need to change the layer name and dimension for feature extraction. The last convolutional layer in ZF is `conv5`, which has 256 filters instead of 512. So just:

``` python
params['layer'] = 'conv5'
params['dimension'] = 256
```

Also for reranking, the layer name should be changed as well in `rerank.py`. [Here](https://github.com/imatge-upc/retrieval-2016-deepvision/blob/master/rerank.py#L76)'s where you should change:

``` python
layer_roi = 'pool5'
```

to

``` python
layer_roi = 'roi_pool_conv5'
```

**Comment by bkj** [comment]
Thanks!
